# Generated by Django 4.2.24 on 2025-09-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="grade",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="max_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quiz",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=250),
        ),
    ]
