# Generated by Django 4.2.24 on 2025-09-14 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0002_quiz_grade_quiz_max_score_quiz_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="difficulty",
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_retry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="max_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="submission",
            name="results",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="performance_metrics",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="submission",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="quiz.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
